#!/bin/bash

# Run Gnoppix hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=gnoppix|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"Gnoppix Linux\"|'
}

Os_release() {
    local file=/etc/os-release
    local gnoppixfile=/usr/lib/gnoppix-release

    sed -i $file \
        -e 's|^NAME=.*$|NAME=\"Gnoppix Linux\"|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=\"Gnoppix\"|' \
        -e 's|^ID=.*$|ID=gnoppix|' \
        -e 's|^ID_LIKE=.*$|ID_LIKE=arch|' \
        -e 's|^ANSI_COLOR=.*$|ANSI_COLOR=\"38;2;23;147;209\"|' \
        -e 's|^HOME_URL=.*$|HOME_URL=\"https://gnoppix.org/\"|' \
        -e 's|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL=\"https://docs.gnoppix.com/\"|' \
        -e 's|^SUPPORT_URL=.*$|SUPPORT_URL=\"https://gnoppix.org/\"|' \
        -e 's|^BUG_REPORT_URL=.*$|BUG_REPORT_URL=\"https://github.com/gnoppix\"|' \
        -e 's|^LOGO=.*$|LOGO=gnoppix|'

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi

    if [ -r $gnoppixfile ] ; then
        # fix BUILD_ID 
        local buildid="$(grep "^VERSION=" $gnoppixfile | awk '{print $1}' | cut -d '=' -f 2)"
        sed -i $file -e "s|^BUILD_ID=.*$|BUILD_ID=$buildid|"
    fi
}

Issues() {
    sed -i 's|Arch Linux|Gnoppix Linux|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
